version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install poetry
    post_install:
      - |
        . "$READTHEDOCS_VIRTUALENV_PATH/bin/activate" \
          && poetry install

sphinx:
  configuration: docs/conf.py
