name: Code quality

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: poetry
      - name: Install dependencies
        run: |
          pipx install poetry
          poetry install --all-extras
      - name: Coding style check
        run: poetry run ruff check .

  type:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: poetry
      - name: Install dependencies
        run: |
          pipx install poetry
          poetry install --all-extras
      - name: Type check
        run: poetry run pyright
