name: Publish

on:
  pull_request: {} # FIXME remove

  push:
    tags:
      - v0.*.*

env:
  # python version for the jobs that does not need to run on all versions
  MAIN_PYTHON_VERSION: "3.9"

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m pip install poetry

      - name: Check version
        run: |
          [[ "xv$(poetry version)" == "x$GITHUB_REF_NAME" ]]

      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: ${{ github.ref }}
          check-name: Run pytest
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20

      - name: Build
        run: |
          poetry build

      # - name: Release to PyPI
      #   run: |
      #     poetry publish -u __token__
