name: Publish

on:
  # TODO still not understand how to trigger publish after test
  push:
    tags:
      - v*

env:
  # python version for the jobs that does not need to run on all versions
  MAIN_PYTHON_VERSION: "3.9"

jobs:
  publish:
    name: Release package to PyPI

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: |
          python -m pip install poetry

      - name: Check version
        run: |
          export PACKAGE_VERSION="$(poetry version --short)"
          export TAG_VERSION="${GITHUB_REF_NAME:1}"

          echo "package version: $PACKAGE_VERSION"
          echo "github ref: $TAG_VERSION"

          [[ "x$PACKAGE_VERSION" == "x$TAG_VERSION" ]]

      - name: Build
        run: |
          poetry build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
