name: Release

on:
  push:
    tags:
      - v*

jobs:
  release-package:
    name: Release package to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
          key: ${{ runner.os }}-python-poetry-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: pip3 install poetry

      - name: Check version
        run: |
          export PACKAGE_VERSION="$(poetry version --short)"
          export TAG_VERSION="${GITHUB_REF_NAME:1}"

          echo "package version: $PACKAGE_VERSION"
          echo "github ref: $TAG_VERSION"

          [[ "x$PACKAGE_VERSION" == "x$TAG_VERSION" ]]

      - run: poetry build

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
